name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      # The smoke test runs a NixOS VM
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: cachix/install-nix-action@v31

      - name: Check flake
        run: nix flake check
